version: "3.9"

services:
  licencias:
    build: ./TareaMicroProveedor
    container_name: licencias
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./TareaMicroProveedor/db:/app/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health || exit 1"]
      interval: 5s
      retries: 5
    networks:
      - app-network

  portal-paciente:
    build: ./TareaMicroPaciente
    container_name: portal-paciente
    ports:
      - "4000:3001"
    environment:
      - NODE_ENV=development
      - LICENSES_SERVICE_URL=http://licencias:3000
    depends_on:
      - licencias
    networks:
      - app-network

  validador-aseguradora:
    build: ./TareaMicroValidadorAseguradora
    container_name: validador-aseguradora
    ports:
      - "5000:3003"
    environment:
      - NODE_ENV=development
      - LICENSES_SERVICE_URL=http://licencias:3000
    depends_on:
      - licencias
    networks:
      - app-network

  consumer-tests:
    build: ./TareaMicroPaciente
    container_name: consumer-tests
    volumes:
      - ./pacts:/app/pacts    # carpeta donde se generan los contratos Pact
    environment:
      - NODE_ENV=test
    depends_on:
      - licencias
    networks:
      - app-network
    # no arrancar automáticamente, se ejecuta con: docker compose run --rm consumer-tests

networks:
  app-network:
    driver: bridge